sudo: false
language: cpp
compiler:
    - clang++
    - g++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
            - boost-latest
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libboost1.55-all-dev
            - cmake

install:
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
    - cd $HOME/build/godai0519/BayesianNetwork
    - mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4 && make test -j4 && cd .. && rm -r ./build
    - mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug   .. && make -j4 && make test -j4 && cd .. && rm -r ./build

